<?php

namespace EventsBundle\Repository;

/**
 * SpeakersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakersRepository extends \Doctrine\ORM\EntityRepository
{
}
